#!/bin/bash
set -euo pipefail

SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_PATH=$(cd "$SCRIPT_PATH/../.." && pwd)

echo "Running pre-commit hooks..."
echo

source "$ROOT_PATH/scripts/run_checks"
